- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with aws"
    DURATION: "120HRS"
    TRAINER: "SKR"
  tasks:
  - name: print the information
    ansible.builtin.dubug:
      msg: "Hi, i am learning {{COURSE}}, Duration is:{{DURATION}}, Trainer: {{TRAINER}} "