- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with aws"
    DURATION: "120HRS"
    TRAINER: "SKR"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, i am learning {{COURSE}}, Duration is:{{DURATION}}, Trainer: {{TRAINER}} "
  
  - name: print the information again
    vars: #task variable override
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, i am learning {{COURSE}}, Duration is:{{DURATION}}, Trainer: {{TRAINER}} "

    