- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      #msg: "Hello {{ course }}"
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to uppercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert to lower
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: get the unique values
    vars:
      numbers: [1,2,3,3,4,4,5,5,6,7,8]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the unique values
    vars:
      numbers: [1,2,3,3,44,5,5,6,7,8]
    ansible.builtin.debug:
      msg: "Min: {{ numbers | min }}, Max: {{ numbers | max }}"

  # - name: convert map to list
  #   vars:
  #     course:
  #       name: "Devops with aws"
  #       duration: 120
  #       trainer: "SKR"
  #     ansible.builtin.debug:
  #       msg: "{{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - { "key": "name", "value": "Devops with aws" }
      - { "key": "Duration", "value": " 120 hrs" }
      - { "key": "Trainer", "value": "AKR" }
    ansible.builtin.debug:
        msg: "{{ course | items2dict }}"